# Generated by Django 3.2.3 on 2021-10-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carton_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.RemoveField(
            model_name='product_on_pallet',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='product_on_pallet',
            name='product',
        ),
        migrations.DeleteModel(
            name='Pallet',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_On_Pallet',
        ),
    ]
