# Generated by Django 3.2.3 on 2021-10-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211012_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('GTIN_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('carton_qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carton_qty')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.style')),
            ],
        ),
    ]
