# Generated by Django 3.2.3 on 2021-10-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products_On_Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, max_length=5)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pallets')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='pallets',
            name='products',
            field=models.ManyToManyField(through='main.Products_On_Pallets', to='main.Product'),
        ),
    ]
