# Generated by Django 3.2.3 on 2021-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211012_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_on_pallets',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
