# Generated by Django 3.2.3 on 2021-10-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_on_pallets_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN_number',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
