# Generated by Django 3.2.3 on 2021-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_gtin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
