# Generated by Django 3.1.2 on 2021-10-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_gtin_number'),
        ('main', '0006_auto_20211023_2117'),
    ]

    operations = [
    ]
