# Generated by Django 3.2.3 on 2021-11-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.pallets')),
            ],
        ),
    ]
