# Generated by Django 3.2.3 on 2021-11-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_location'),
        ('main', '0011_locations'),
    ]

    operations = [
    ]
