# Generated by Django 3.2.3 on 2021-11-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211112_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='pallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pallets'),
        ),
    ]
