# Generated by Django 3.2.3 on 2021-11-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_locations_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='pallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pallets'),
        ),
    ]
