# Generated by Django 3.2.3 on 2021-11-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_locations_pallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='quantity',
        ),
    ]
